# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnPush = QtWidgets.QPushButton(self.centralwidget)
        self.btnPush.setGeometry(QtCore.QRect(100, 150, 191, 121))
        self.btnPush.setObjectName("btnPush")
        self.btnToggle = QtWidgets.QPushButton(self.centralwidget)
        self.btnToggle.setGeometry(QtCore.QRect(110, 310, 191, 141))
        self.btnToggle.setCheckable(True)
        self.btnToggle.setChecked(False)
        self.btnToggle.setObjectName("btnToggle")
        self.lblColor = QtWidgets.QLabel(self.centralwidget)
        self.lblColor.setGeometry(QtCore.QRect(460, 160, 191, 111))
        self.lblColor.setObjectName("lblColor")
        self.lblState = QtWidgets.QLabel(self.centralwidget)
        self.lblState.setGeometry(QtCore.QRect(440, 310, 181, 131))
        self.lblState.setObjectName("lblState")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnPush.setText(_translate("MainWindow", "색상 변경"))
        self.btnToggle.setText(_translate("MainWindow", "OFF"))
        self.lblColor.setText(_translate("MainWindow", "TextLabel"))
        self.lblState.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
